#!/bin/bash
function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --with-shared \
    --without-debug \
    --enable-widec
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no tests"
}

function install_commands()
{
  make install &&
  mv -v /usr/lib/libncursesw.so.5* /lib &&
  ln -sfv ../../lib/libncursesw.so.5 /usr/lib/libncursesw.so &&
  for lib in ncurses form panel menu ; do \
    rm -vf /usr/lib/lib${lib}.so ; \
    echo "INPUT(-l${lib}w)" >/usr/lib/lib${lib}.so ; \
    ln -sfv lib${lib}w.a /usr/lib/lib${lib}.a ; \
  done &&
  ln -sfv libncurses++w.a /usr/lib/libncurses++.a &&
  rm -vf /usr/lib/libcursesw.so &&
  echo "INPUT(-lncursesw)" >/usr/lib/libcursesw.so &&
  ln -sfv libncurses.so /usr/lib/libcurses.so &&
  ln -sfv libncursesw.a /usr/lib/libcursesw.a &&
  ln -sfv libncurses.a /usr/lib/libcurses.a &&
  mkdir -v       /usr/share/doc/ncurses-5.9 &&
  cp -v -R doc/* /usr/share/doc/ncurses-5.9 &&
  echo "INSTALL COMPLETE"
}
