#!/bin/bash

CFLAGS="$CFLAGS -fno-tree-pre"
CXXFLAGS="$CXXFLAGS -fno-tree-pre"
CPPFLAGS="$CPPFLAGS $(pkg-config --cflags libffi)"

function configure_commands()
{
  tar -xf ~/src/clang-3.0.tar.gz -C tools &&
  mv tools/clang-3.0.src tools/clang &&

  touch tools/edis/EnhancedDisassembly.exports &&

#  sed -i -e 's:\$(PROJ_prefix)/etc/llvm:/etc/llvm:'                      \
#         -e 's:\$(PROJ_prefix)/lib:$(PROJ_prefix)/lib/llvm:'             \
#         -e 's:\$(PROJ_prefix)/docs/llvm:$(PROJ_prefix)/share/doc/llvm:' \
#      Makefile.config.in  &&
  sed -i -e 's:\$(PROJ_prefix)/etc/llvm:/etc/llvm:'                      \
         -e 's:\$(PROJ_prefix)/docs/llvm:$(PROJ_prefix)/share/doc/llvm:' \
      Makefile.config.in  &&

  sed -i 's:$(RPATH) -Wl,$(\(ToolDir\|LibDir\|ExmplDir\))::g' \
      Makefile.rules &&

  CC=gcc \
    CXX=g++ \
      ./configure \
        --prefix=/usr              \
        --sysconfdir=/etc          \
        --enable-shared            \
        --enable-libffi            \
        --enable-targets=all       \
        --disable-expensive-checks \
        --disable-debug-runtime    \
        --disable-assertions       \
        --enable-optimized
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
