#!/bin/bash

export BUILD_DIR=${HOME}/build_llvm
export CFLAGS="$CFLAGS -fno-tree-pre"
export CXXFLAGS="$CXXFLAGS -fno-tree-pre"
export CPPFLAGS="$CPPFLAGS $(pkg-config --cflags libffi)"

function configure_commands()
{
  # -DLLVM_TARGETS_TO_BUILD="host;AMDGPU" \
  LLVM_VER=3.9.0
  set -x #echo on
  LLVM_SRC_DIR=${HOME}/llvm-${LLVM_VER}.src
  pushd $LLVM_SRC_DIR &&
  tar -xf ${HOME}/src-extra/cfe-${LLVM_VER}.src.tar.* -C tools &&
  mv tools/cfe-${LLVM_VER}.src tools/clang &&
  echo "cfe-${LLVM_VER}.src" >> ~/.project &&
  popd &&
  CC=gcc \
    CXX=g++ \
    cmake \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DLLVM_ENABLE_FFI=ON \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=ON \
      -DLLVM_TARGETS_TO_BUILD="host;AMDGPU" \
      -Wno-dev \
      $LLVM_SRC_DIR
}

function make_commands()
{
  make
}

function test_commands()
{
  # make -k check || echo "Darn $? ... oh, well."
  echo "tests hang, foget it"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
