#!/bin/bash

function configure_commands()
{
  cd ~/xvid*/build/generic &&
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  cd ~/xvid*/build/generic &&
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  cd build/generic &&
  make install &&
  chmod -v 755 /usr/lib/libxvidcore.so.4.3 &&
  ln -v -sf libxvidcore.so.4.3 /usr/lib/libxvidcore.so.4 &&
  ln -v -sf libxvidcore.so.4   /usr/lib/libxvidcore.so   &&
  install -v -m755 -d /usr/share/doc/xvidcore-1.3.2/examples &&
  install -v -m644 ../../doc/* /usr/share/doc/xvidcore-1.3.2 &&
  install -v -m644 ../../examples/* \
    /usr/share/doc/xvidcore-1.3.2/examples &&
  echo "INSTALL COMPLETE"
}
