#!/bin/bash

# override CFLAGS, CXXFLAGS, or other environment variables here
# as needed.
#
# If the package needs to be built from a directory other than
# the source directory, set BUILD_DIR appropriately (for example:
# 'export BUILD_DIR=../build-binutils')

export BUILD_DIR=../build-glibc

function configure_commands()
{
    LINKER=$(readelf -l /tools/bin/bash | sed -n 's@.*interpret.*/tools\(.*\)]$@\1@p')
    sed -i "s|libs -o|libs -L/usr/lib -Wl,-dynamic-linker=${LINKER} -o|" \
      ${HOME}/glibc-*/scripts/test-installation.pl
    unset LINKER
    sed -i 's/\\$$(pwd)/`pwd`/' ${HOME}/glibc-*/timezone/Makefile
    ../glibc-*/configure \
      --prefix=/usr \
      --disable-profile \
      --enable-kernel=3.6.0 \
      --libexecdir=/usr/lib/glibc \
      --enable-obsolete-rpc
}

function make_commands()
{
  make
}

function test_commands()
{
  make -k check 2>&1 | tee glibc-check-log
  grep Error glibc-check-log
  echo "whatever"
}

function install_commands()
{
  touch /etc/ld.so.conf &&
  make install &&
  rm -v /usr/include/rpcsvc/*.x &&
  cp -v ../glibc-2.19/nscd/nscd.conf /etc/nscd.conf &&
  mkdir -pv /var/cache/nscd &&
  echo "INSTALL COMPLETE"
}
