#!/bin/bash

function configure_commands()
{
  sed -i "/seems to be moved/s/^/#/" ltmain.sh &&
  ./configure \
    --prefix=/usr \
    --with-x11
}

function make_commands()
{
  make
}

function test_commands()
{
  make -k check || echo "Darn $? ... oh, well ...."
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
