#!/bin/bash

export QTDIR=/opt/qt
export PATH=$PATH:/opt/qt/bin
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/qt/lib/pkgconfig

function configure_commands()
{
  # --disable-qt4 \
  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --with-avahi-user=avahid \
    --disable-static \
    --disable-mono \
    --disable-monodoc \
    --disable-qt3 \
    --enable-core-docs \
    --enable-compat-libdns_sd \
    --disable-python \
    --with-distro=none
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
