#!/bin/bash

function configure_commands()
{
  PAGE=A4 \
   ./configure \
     --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no tests"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
