#!/bin/bash

function configure_commands()
{
  cd source3 &&
  sed -i \
    -e "s/python2.6 python2.5/python2.7 &/" \
    -e "s/python2.6-config python2.5-config/python2.7-config &/" \
     configure &&
  ./configure                          \
    --prefix=/usr                      \
    --sysconfdir=/etc                  \
    --localstatedir=/var               \
    --with-piddir=/run/samba           \
    --with-pammodulesdir=/lib/security \
    --with-fhs                         \
    --enable-nss-wrapper               \
    --enable-socket-wrapper            &&
  sed -i "s/-ldl/& -ltirpc -lpthread/" Makefile
}

function make_commands()
{
  cd source3 &&
  make
}

function test_commands()
{
  cd source3 &&
  make test
}

function install_commands()
{
  cd source3 &&
  make install &&
  install -v -m644 pkgconfig/*.pc /usr/lib/pkgconfig        &&
  install -v -m755 ../nsswitch/libnss_win{s,bind}.so /lib   &&
  ln -v -sf libnss_winbind.so /lib/libnss_winbind.so.2      &&
  ln -v -sf libnss_wins.so    /lib/libnss_wins.so.2         &&
  install -v -m644 ../examples/smb.conf.default /etc/samba  &&
  if [ -d /etc/openldap/schema ]; then
    install -v -m644    ../examples/LDAP/README              \
                        /etc/openldap/schema/README.LDAP     &&
    install -v -m644    ../examples/LDAP/samba*              \
                        /etc/openldap/schema                 &&
    install -v -m755    ../examples/LDAP/{convert*,get*,ol*} \
                        /etc/openldap/schema                 &&
    echo "ldap done"
  fi &&
  install -v -m755 -d /usr/share/doc/samba-3.6.12 &&
  install -v -m644    ../docs/*.pdf \
                      /usr/share/doc/samba-3.6.12 &&
  ln -v -s ../../samba/swat  /usr/share/doc/samba-3.6.12 &&
  echo "INSTALL COMPLETE"
}
