#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --docdir=/usr/share/doc/man-db-2.6.7.1 \
    --sysconfdir=/etc \
    --disable-setuid \
    --with-browser=/usr/bin/lynx \
    --with-vgrind=/usr/bin/vgrind \
    --with-grap=/usr/bin/grap
}

function make_commands()
{
  make
}

function test_commands()
{
  make check || echo "DARN $?"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
