#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --docdir=/usr/share/doc/xz-5.0.5
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  mv -v /usr/bin/{xz,lzma,lzcat,unlzma,unxz,xzcat} /bin &&
  mv -v /usr/lib/liblzma.so.* /lib &&
  ln -sfv ../../lib/$(readlink /usr/lib/liblzma.so) /usr/lib/liblzma.so &&
  echo "INSTALL COMPLETE"
}
