#!/bin/bash

function configure_commands()
{
  sed -i -e 's@\*/module.mk@proc/module.mk ps/module.mk@' Makefile
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no tests"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
