#!/bin/bash

function configure_commands()
{
  export SRCDIR=`pwd` &&
  sed -i s/500/5000/ generic/regc_nfa.c &&
  cd unix &&
  ./configure \
    --prefix=/usr
  unset SRCDIR
}

function make_commands()
{
  export SRCDIR=`pwd` &&
  cd unix &&
  make &&
  sed -e "s#$SRCDIR/unix#/usr/lib#" \
    -e "s#$SRCDIR#/usr/include#"  \
    -i tclConfig.sh               &&
  sed -e "s#$SRCDIR/unix/pkgs/tdbc1.0.4#/usr/lib/tdbc1.0.4#" \
    -e "s#$SRCDIR/pkgs/tdbc1.0.4/generic#/usr/include#"    \
    -e "s#$SRCDIR/pkgs/tdbc1.0.4/library#/usr/lib/tcl8.6#" \
    -e "s#$SRCDIR/pkgs/tdbc1.0.4#/usr/include#"            \
    -i pkgs/tdbc1.0.4/tdbcConfig.sh                        &&
  sed -e "s#$SRCDIR/unix/pkgs/itcl4.0.5#/usr/lib/itcl4.0.5#" \
    -e "s#$SRCDIR/pkgs/itcl4.0.5/generic#/usr/include#"    \
    -e "s#$SRCDIR/pkgs/itcl4.0.5#/usr/include#"            \
    -i pkgs/itcl4.0.5/itclConfig.sh                        &&
  unset SRCDIR
}

function test_commands()
{
  cd unix &&
  TZ=UTC make test
}

function install_commands()
{
  cd unix &&
  make install &&
  make install-private-headers &&
  #ln -sv tclsh8.6 /bin/tclsh &&
  chmod -v 755 /usr/lib/libtcl8.6.so
  echo "INSTALL COMPLETE"
}
