#!/bin/bash

function configure_commands()
{
  sed -i s/500/5000/ generic/regc_nfa.c &&
  cd unix &&
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  cd unix &&
  make
}

function test_commands()
{
  cd unix &&
  TZ=UTC make test
}

function install_commands()
{
  cd unix &&
  make install &&
  make install-private-headers &&
  ln -sv tclsh8.6 /bin/tclsh &&
  echo "INSTALL COMPLETE"
}
