#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr  \
    --libexecdir=/usr/sbin \
    --localstatedir=/var   \
    --disable-ifconfig     \
    --disable-logger       \
    --disable-syslogd      \
    --disable-whois        \
    --disable-servers
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  make -C doc html &&
  make -C doc install-html docdir=/usr/share/doc/inetutils-1.9.1 &&
  mv -v /usr/bin/{hostname,ping,ping6} /bin &&
  mv -v /usr/bin/traceroute /sbin &&
  echo "INSTALL COMPLETE"
}
