#!/bin/bash

function configure_commands()
{
  perl Makefile.PL
}

function make_commands()
{
  make
}

function test_commands()
{
  make test
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
