#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  sed -i -e '41s/ENOENT/& || errno == EINVAL/' \
    tests/test-readlink.h &&
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
