#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --with-gitconfig=/etc/gitconfig
}

function make_commands()
{
  make
}

function test_commands()
{
  make test
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
