#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --enable-shared
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install  &&
  install -v -m755 -d /usr/share/doc/nettle-2.4 &&
  install -v -m644 nettle.html /usr/share/doc/nettle-2.4 &&
  echo "INSTALL COMPLETE"
}
