#!/bin/bash
function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --with-pcre=system
}

function make_commands()
{
  make
}

function test_commands()
{
  # make -k check || echo "DARN $? Oh, well."
  echo "tests hang, forget it."
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
