#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  install -v -m755 -d /usr/share/doc/libgcrypt-1.5.0 &&
  install -v -m644    README doc/{README.apichanges,fips*,libgcrypt*} \
                      /usr/share/doc/libgcrypt-1.5.0 &&
  echo "INSTALL COMPLETE"
}
