#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --with-rootprefix="" \
    --libexecdir=/lib \
    --enable-split-usr \
    --libdir=/usr/lib \
    --with-rootlibdir=/lib \
    --sbindir=/sbin \
    --bindir=/sbin \
    --enable-rule_generator \
    --disable-introspection \
    --disable-keymap \
    --disable-gudev \
    --disable-gtk-doc-html \
    --with-firmware-path=/lib/firmware \
    --enable-libkmod
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  install -dv /lib/firmware &&
  echo "# dummy, so that network is once again on eth*" \
    > /etc/udev/rules.d/80-net-name-slot.rules &&
  echo "INSTALL COMPLETE"
}
