#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  install -v -m755 -d /usr/share/doc/imlib2-1.4.5 &&
  install -v -m644    doc/{*.gif,index.html} \
                      /usr/share/doc/imlib2-1.4.5 &&
  echo "INSTALL COMPLETE"
}
