#!/bin/bash

function configure_commands()
{
  sed -i "/seems to be moved/s/^/#/" ltmain.sh &&
  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
