#!/bin/bash

CFLAGS="-g -O2 $([ $(uname -m) = x86_64 ] && echo -fPIC)"

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --enable-shared \
    --disable-static
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  cp liba52/a52_internal.h /usr/include/a52dec &&
  install -v -m644 -D doc/liba52.txt \
    /usr/share/doc/liba52-0.7.4/liba52.txt &&
  echo "INSTALL COMPLETE"
}


# override CFLAGS, CXXFLAGS, or other environment variables here
# as needed.
#
# If the package needs to be built from a directory other than
# the source directory, set BUILD_DIR appropriately (for example:
# 'export BUILD_DIR=../build-binutils')
#
# You may copy a source tarball into a "src" subdirectory, and
# put patches into a "patches" subdirectory, in which case the
# build script will unpack and patch the source for you.
# Alternatively, you can prepare the source yourself (and cd into
# the source directory) before running build.
#
# If necessary, redefine the build functions:
#   configure_commands, make_commands, test_commands, install_commands
#
# If this package has external dependencies, such as requiring
# special users or groups to exist, verify that the dependencies
# are met in initial_checkup (echo problem notifications and exit
# if they are not).
#
# Look at ~/.bash_profile for syntax help.  Re-source the options
# file afterward!
#
# Run "declare -f" to find out the current function definitions.
#
