#!/bin/bash

CFLAGS="-g -O2 $([ $(uname -m) = x86_64 ] && echo -fPIC)"

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --enable-shared \
    --disable-static
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  cp liba52/a52_internal.h /usr/include/a52dec &&
  install -v -m644 -D doc/liba52.txt \
    /usr/share/doc/liba52-0.7.4/liba52.txt &&
  echo "INSTALL COMPLETE"
}
