#!/bin/bash

function configure_commands()
{
  sed -i 's#) ytasm.*#)#' Makefile.in &&
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
