#!/bin/bash

function configure_commands()
{
  PKG_CONFIG_PATH="/tools/lib/pkgconfig" \
    ./configure \
      --prefix=/usr \
      --disable-vlock \
      --enable-optional-progs
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  mv -v /usr/bin/{dumpkeys,kbd_mode,loadkeys,setfont} /bin &&
  mkdir -v /usr/share/doc/kbd-2.0.1 &&
  cp -R -v docs/doc/* /usr/share/doc/kbd-2.0.1 &&
  echo "INSTALL COMPLETE"
}
