#!/bin/bash

function configure_commands()
{
  sed -i '/guardado\ el/s/\(^.*en\ %\)\(.*\)/\14\$\2/' po/es.po &&
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no test"
}

function install_commands()
{
  make install &&
  mv -v /usr/bin/{kbd_mode,dumpkeys,loadkeys,openvt,setfont} /bin &&
  mkdir -v /usr/share/doc/kbd-1.15.3 &&
  cp -R -v doc/* /usr/share/doc/kbd-1.15.3 &&
  echo "INSTALL COMPLETE"
}
