#!/bin/bash

function configure_commands()
{
  cmake CMakeLists.txt
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
