#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib/dbus-1.0 \
    --localstatedir=/var
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  mv -v /usr/share/doc/dbus \
        /usr/share/doc/dbus-1.4.20
  echo "INSTALL COMPLETE"
}
