#!/bin/bash

export DBUS_VER=1.10.10

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib/dbus-1.0 \
    --localstatedir=/var \
    --disable-doxygen-docs \
    --disable-xml-docs \
    --disable-static \
    --disable-systemd \
    --without-systemdsystemunitdir \
    --with-console-auth-dir=/run/console/ \
    --docdir=/usr/share/doc/dbus-$DBUS_VER
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
