#!/bin/bash

function configure_commands()
{
  sed -e '/^includesdir/ s/$(libdir).*$/$(includedir)/' \
    -i include/Makefile.in &&
  sed -e '/^includedir/ s/=.*$/=@includedir@/' \
    -e 's/^Cflags: -I${includedir}/Cflags:/' \
    -i libffi.pc.in &&
    ./configure \
      --prefix=/usr \
      --disable-static
}

function make_commands()
{
  make
}

function test_commands()
{
  make -k check || echo "DARN $? ... oh, well."
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
