#!/bin/bash

function configure_commands()
{
  xmkmf
}

function make_commands()
{
  make World
}

function test_commands()
{
  : make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
