#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --disable-static \
    --without-gnome
}

function make_commands()
{
  make
}

function test_commands()
{
  make -k check || echo "Darn $? ... oh, well."
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
