#!/bin/bash

function configure_commands()
{
  echo " no ./configure --prefix=/usr"
}

function make_commands()
{
  make CPPFLAGS="-fPIC" linux
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make INSTALL_TOP=/usr install &&
  mkdir -pv /usr/share/lua/5.1 &&
  mkdir -pv /usr/lib/lua/5.1 &&
  sed -i 's@/usr/local@/usr@g' etc/lua.pc &&
  cp etc/lua.pc /usr/lib/pkgconfig &&
  cp etc/lua.ico /usr/share/icons &&
  echo "INSTALL COMPLETE"
}
