#!/bin/bash

export QTDIR=/opt/qt
export PATH=$PATH:/opt/qt/bin
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/qt/lib/pkgconfig

function configure_commands()
{
# --disable-lua
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make -j1
}

function test_commands()
{
  make -j1 -k check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
