#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --with-socket-dir=/var/run/screen \
    --with-sys-screenrc=/etc/screenrc &&
  sed -i -e "s%/usr/local/etc/screenrc%/etc/screenrc%" {etc,doc}/*
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  install -m 644 etc/etcscreenrc /etc/screenrc &&
  echo "INSTALL COMPLETE"
}
