#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --docdir=/usr/share/doc/gettext-0.18.1.1
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
