#!/bin/bash

export GETTEXT_VERSION=0.19.1

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --docdir=/usr/share/doc/gettext-${GETTEXT_VERSION}
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
