#!/bin/bash

function configure_commands()
{
  /opt/qt-4.8.1/bin/qmake \
    pokerth_game.pro
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
