#!/bin/bash

function configure_commands()
{
  ./autogen.sh &&
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make -k check || echo "DARN $?"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
