#!/bin/bash

function configure_commands()
{
  sed -i '/^TARGETS/s@arpd@@g' misc/Makefile &&
  sed -i /ARPD/d Makefile &&
  sed -i 's/arpd.8//' man/man8/Makefile
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no tests"
}

function install_commands()
{
  make DOCDIR=/usr/share/doc/iproute2-3.14.0 install &&
  echo "INSTALL COMPLETE"
}
