#!/bin/bash

function configure_commands()
{
  echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h &&
  ./configure \
    --prefix=/usr \
    --enable-multibyte
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "skipping this"
}

function install_commands()
{
  make install &&
  ln -sv vim /usr/bin/vi &&
  ln -sv ../vim/vim74/doc /usr/share/doc/vim-7.4 &&
  echo "INSTALL COMPLETE"
}
