#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr &&
  makeinfo --html --no-split -o doc/dejagnu.html doc/dejagnu.texi &&
  makeinfo --plaintext       -o doc/dejagnu.txt  doc/dejagnu.texi
}

function make_commands()
{
  make
}

function test_commands()
{
  make -k check || echo "DARN $? ... oh, well."
}

function install_commands()
{
  make install &&
  install -v -dm755 /usr/share/doc/dejagnu-1.6 &&
  install -v -m644 doc/dejagnu.{html,txt} /usr/share/doc/dejagnu-1.6 &&
  echo "INSTALL COMPLETE"
}
