#!/bin/bash

function configure_commands()
{
  sed -i 's/\(.*gtkdoc-rebase --relative.* \)\(;.*\)/\1|| true\2/' \
    docs/{gst,libs}/Makefile.in &&
  ./configure \
     --prefix=/usr \
     --libexecdir=/usr/lib
}

function make_commands()
{
  make
}

function test_commands()
{
  make -k check || echo "Darn $? ... oh, well."
}

function install_commands()
{
  make install &&
  install -v -m755 -d /usr/share/doc/gstreamer-0.10/design &&
  install -v -m644 docs/design/*.txt \
                    /usr/share/doc/gstreamer-0.10/design &&
  echo "INSTALL COMPLETE"
}
