#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --program-suffix=-1
}

function make_commands()
{
  make GETTEXT_PACKAGE=libwnck-1
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make GETTEXT_PACKAGE=libwnck-1 install &&
  echo "INSTALL COMPLETE"
}
