#!/bin/bash

function configure_commands()
{
  CC="gcc -isystem /usr/include" \
  LDFLAGS="-Wl,-rpath-link,/usr/lib:/lib" \
  ./configure \
    --prefix=/usr \
    --docdir=/usr/share/doc/mpc-1.0.2
}

function make_commands()
{
  make &&
  make html
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  make install-html &&
  echo "INSTALL COMPLETE"
}
