#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --with-gtk=3.0 \
    --disable-examples
}

function make_commands()
{
  make
}

function test_commands()
{
  make -k check || echo "Darn $? ... oh, well."
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
