#!/bin/bash

function configure_commands()
{
    ./configure --prefix=/usr --with-readline \
    --mandir=/usr/share/man --infodir=/usr/share/info
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "quit" | ./bc/bc -l Test/checklib.b
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
