#!/bin/bash

function configure_commands()
{
 :
}

function make_commands()
{
  make -f makefile.unix
}

function test_commands()
{
  : make check
}

function install_commands()
{
  install -v -m755 unrar /usr/bin &&
  echo "INSTALL COMPLETE"
}
