#!/bin/bash

function configure_commands()
{
  ./waf configure \
    --prefix=/usr
}

function make_commands()
{
  ./waf build
}

function test_commands()
{
  echo "skiping tests"
}

function install_commands()
{
  ./waf install &&
  echo "INSTALL COMPLETE"
}
