#!/bin/bash
function configure_commands()
{
  sed -i -e 's@etc/adjtime@var/lib/hwclock/adjtime@g' \
    $(grep -rl '/etc/adjtime' .) &&
  mkdir -pv /var/lib/hwclock &&
  ./configure \
    --enable-write \
    --docdir=/usr/share/doc/util-linux-2.24.2
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "tests require chown -Rv nobody, forget it"
}

function install_commands()
{
  make install &&
  mv -v /usr/bin/logger /bin &&
  echo "INSTALL COMPLETE"
}
