#!/bin/bash
function configure_commands()
{
  sed -i 's@etc/adjtimer@var/lib/hwclock/sdjtime@g' \
    hwclock/hwclock.c &&
  mkdir -p /var/lib/hwclock &&
  ./configure
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no tests"
}

function install_commands()
{
  make install &&
  mv -v /usr/bin/logger /bin &&
  echo "INSTALL COMPLETE"
}
