#!/bin/bash

export QTDIR=/opt/qt
export PATH=$PATH:/opt/qt/bin
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/qt/lib/pkgconfig

function configure_commands()
{
  # CONFIG+=no-speechd \
  qmake \
    CONFIG+=no-g15 \
    CONFIG+=no-server \
    main.pro \
    -recursive
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  cp -v release/mumble* /usr/bin/ &&
  echo "INSTALL COMPLETE"
}
