#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-static \
    --docdir=/usr/share/doc/xfce4-panel-4.10.0
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
