#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib/GConf \
    --disable-orbit \
    --disable-static
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  install -v -m755 -d /etc/gconf/gconf.xml.system &&
  echo "INSTALL COMPLETE"
}
