#!/bin/bash

function configure_commands()
{
    ./configure \
      CHECK_CFLAGS=-I/tools/include \
      CHECK_LIBS="-L/tools/lib -lcheck" \
      --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
