#!/bin/bash

function configure_commands()
{
  PKG_CONFIG_PATH=/tools/lib/pkgconfig \
   ./configure \
     --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
