#!/bin/bash

function configure_commands()
{
  ./configure \
    --with-systemdsystemunitdir=no
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
