#!/bin/bash

function configure_commands()
{
  sed -i '/DG_DISABLE_DEPRECATED/d' glade/Makefile.in &&
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make -k check || echo "Darn $? test-convert is known to fail"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
