#!/bin/bash

function configure_commands()
{
  sed -i 's#save_errno#aprerr#' subversion/mod_dav_svn/util.c &&
  ./configure \
    --prefix=/usr \
    --disable-static
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make -j1 install &&
  install -v -m755 -d /usr/share/doc/subversion-1.7.4 &&
  cp -v -R doc/* \
    /usr/share/doc/subversion-1.7.4 &&
  echo "INSTALL COMPLETE"
}
