#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  install -v -m755 -d /usr/share/doc/SDL-1.2.15/html &&
  install -v -m644 docs/html/*.html \
                      /usr/share/doc/SDL-1.2.15/html &&
  echo "INSTALL COMPLETE"
}
