#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  install -v -m755 -d /usr/share/doc/libtasn1-2.12 &&
  install -v -m644    doc/libtasn1.{html,pdf,ps} \
                      /usr/share/doc/libtasn1-2.12 &&
  echo "INSTALL COMPLETE"
}
