#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  install -v -m755 -d /usr/share/doc/aspell-0.60.6.1/aspell{,-dev}.html &&
  install -v -m644 manual/aspell.html/* \
    /usr/share/doc/aspell-0.60.6.1/aspell.html &&
  install -v -m644 manual/aspell-dev.html/* \
    /usr/share/doc/aspell-0.60.6.1/aspell-dev.html &&
  install -v -m 755 scripts/ispell /usr/bin/ &&
  install -v -m 755 scripts/spell /usr/bin/ &&
  echo "INSTALL COMPLETE"
}
