#!/bin/bash

function configure_commands()
{
  CC="gcc -isystem /usr/include" \
  LDFLAGS="-Wl,-rpath-link,/usr/lib:/lib" \
    ./configure \
       --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  mkdir -pv /usr/share/gdb/auto-load/usr/lib &&
  mv -v /usr/lib/libisl*gdb.py /usr/share/gdb/auto-load/usr/lib &&
  echo "INSTALL COMPLETE"
}
