#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --datadir=/usr/share/misc \
    --disable-zlib
}

function make_commands()
{
  make
}

function test_commands()
{
  : make check
}

function install_commands()
{
  make install &&
  mv -v /usr/sbin/update-usbids.sh /usr/sbin/update-usbids &&
  echo "INSTALL COMPLETE"
}
