#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  install -v -m644 -D doc/I18N-HOWTO \
    /usr/share/doc/intltool-0.50.0/I18N-HOWTO &&
  echo "INSTALL COMPLETE"
}
