#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --enable-nls \
    --with-ncurses \
    --with-libtool \
    --enable-widec
}

function make_commands()
{
  make
}

function test_commands()
{
  : make check
}

function install_commands()
{
  make install &&
  chmod -v 755 /usr/lib/libdialog.so.*.*.* &&
  echo "INSTALL COMPLETE"
}
