#!/bin/bash

function configure_commands()
{
  sed -i "/pthread-stubs/d" configure.ac  &&
  autoreconf -fiv &&
  ./configure \
     --prefix=/usr \
     --enable-udev
}

function make_commands()
{
  make
}

function test_commands()
{
  echo 'skip make check'
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
