#!/bin/bash

export SOURCE_DIR_PREFIX=sqlite



function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --disable-static \
    CFLAGS="-g -O2 -DSQLITE_ENABLE_FTS3=1 \
      -DSQLITE_ENABLE_COLUMN_METADATA=1 \
      -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 \
      -DSQLITE_SECURE_DELETE=1 \
      -DSQLITE_ENABLE_DBSTAT_VTAB=1"
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
