#!/bin/bash

function configure_commands()
{
 :
}

function make_commands()
{
  make \
   PREFIX=/usr \
   CC="gcc -fPIC" \
   SHAREDIR=/usr/share/misc \
   MANDIR=/usr/share/man \
   ZLIB=no \
   SHARED=yes \
   all
}

function test_commands()
{
  : make check
}

function install_commands()
{
  make PREFIX=/usr SHARED=yes install &&
  make PREFIX=/usr SHARED=yes install-lib &&
  echo "INSTALL COMPLETE"
}
