#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --with-binsubdir=sbin
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  install -v -m755 -d /usr/share/doc/ntp-4.2.6p4 &&
  cp -v -R html/* /usr/share/doc/ntp-4.2.6p4/ &&
  echo "INSTALL COMPLETE"
}
