#!/bin/bash

export BUILD_DIR=../build-gcc

function configure_commands()
{
  sed -i 's@\./fixinc\.sh@-c true@' ../gcc-*/gcc/Makefile.in &&
  SED=sed CC="gcc -isystem /usr/include" \
  CXX="g++ -isystem /usr/include" \
  LDFLAGS="-Wl,-rpath-link,/usr/lib:/lib" \
  ../gcc-4.8.3/configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --enable-threads=posix \
    --enable-__cxa_atexit \
    --enable-clocale=gnu \
    --enable-languages=c,c++ \
    --disable-multilib \
    --disable-libstdcxx-pch \
    --with-system-zlib \
    --enable-checking=release \
    --enable-libstdcxx-time
}

function make_commands()
{
  make
}

function test_commands()
{
  ulimit -s 32768 &&
  make -k check || echo "DARN $? oh well...."
  ../gcc*/contrib/test_summary | grep -A7 Summ
}

function install_commands()
{
  make install &&
  cp -v ../gcc-4.8.3/include/libiberty.h /usr/include &&
  ln -sv ../usr/bin/cpp /lib &&
  ln -sv gcc /usr/bin/cc &&
  mv -v /usr/lib/libstdc++*gdb.py /usr/share/gdb/auto-load/usr/lib &&
  echo "INSTALL COMPLETE"
}
