#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --disable-static
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  mkdir -p /usr/share/doc/freeglut-2.8.0 &&
  cp doc/*.{html,png} /usr/share/doc/freeglut-2.8.0 &&
  echo "INSTALL COMPLETE"
}
