#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --libdir=/lib \
    --docdir=/usr/share/doc/readline-6.3
}

function make_commands()
{
  make SHLIB_LIBS=-lncurses
}

function test_commands()
{
  echo "no tests"
}

function install_commands()
{
  make SHLIB_LIBS=-lncurses htmldir=/usr/share/doc/readline-6.3 install &&
  mv -v /lib/lib{readline,history}.a /usr/lib &&
  ln -svf ../../lib/$(readlink /lib/libreadline.so) /usr/lib/libreadline.so &&
  ln -svf ../../lib/$(readlink /lib/libhistory.so) /usr/lib/libhistory.so &&
  rm -v /lib/lib{readline,history}.so &&
  echo "INSTALL COMPLETE"
}
