#!/bin/bash

# override CFLAGS, CXXFLAGS, or other environment variables here
# as needed.

export BUILD_DIR=../build-binutils

function configure_commands()
{
  CC="gcc -isystem /usr/include" \
  LDFLAGS="-Wl,-rpath-link,/usr/lib:/lib" \
  ../binutils-2.24/configure \
    --prefix=/usr \
    --enable-shared
}

function make_commands()
{
  make tooldir=/usr
}

function test_commands()
{
  make -k check &&
  echo "YAY tests" || echo "DARN $? oh well"
}

function install_commands()
{
  make tooldir=/usr install &&
  # cp -v ../binutils*/include/libiberty.h /usr/include &&
  echo "INSTALL COMPLETE"
}
