#!/bin/bash

export BUILD_DIR=../build-binutils

function configure_commands()
{
  rm -fv ~/binutils-*/etc/standards.info &&
  sed -i.bak '/^INFO/s/standards.info //' \
    ~/binutils-*/etc/Makefile.in &&
  sed -i "/exception_defines.h/d" \
    ~/binutils-*/ld/testsuite/ld-elf/new.cc &&
  sed -i "s/-fvtable-gc //" \
    ~/binutils-*/ld/testsuite/ld-selective/selective.exp &&
  ../binutils-2.22/configure \
    --prefix=/usr \
    --enable-shared
}

function make_commands()
{
  make tooldir=/usr
}

function test_commands()
{
  make -k check &&
  echo "YAY tests" || echo "DARN $? oh well"
}

function install_commands()
{
  make tooldir=/usr install &&
  cp -v ../binutils*/include/libiberty.h /usr/include &&
  echo "INSTALL COMPLETE"
}
