#!/bin/bash

function configure_commands()
{
 :
  # cd src &&
  # ./configure \
  #  --prefix=/usr
}

function make_commands()
{
  cd src &&
  make
}

function test_commands()
{
  cd src &&
  make check
}

function install_commands()
{
  cd src &&
  make install &&
  echo "INSTALL COMPLETE"
}
