#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  install -v -m755 -d /usr/share/doc/gnutls-3.0.19 &&
  install -v -m644    doc/*.{html,png,eps,pdf,ps} doc/cyclo/*.html \
                      /usr/share/doc/gnutls-3.0.19 &&
  cp -v -R            doc/credentials \
                    /usr/share/doc/gnutls-3.0.19 &&
  echo "INSTALL COMPLETE"
}
