#!/bin/bash
function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --enable-shared \
    --with-gmp=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  make html &&
  make install-html &&
  echo "INSTALL COMPLETE"
}
