#!/bin/bash

function configure_commands()
{
  CC="gcc -isystem /usr/include" \
    LDFLAGS="-Wl,-rpath-link,/usr/lib:/lib" \
    ./configure \
      --prefix=/usr \
      --with-gmp=/usr \
      --docdir=/usr/share/doc/mpfr-3.1.2
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
