#!/bin/bash

function configure_commands()
{
  pushd nspr &&
  sed -ri 's#^(RELEASE_BINS =).*#\1#' pr/src/misc/Makefile.in &&
  sed -i 's#$(LIBRARY) ##' config/rules.mk &&
  ./configure \
    --prefix=/usr \
    --with-mozilla \
    --with-pthreads \
    $([ $(uname -m) = x86_64 ] && echo --enable-64bit) &&
  popd
}

function make_commands()
{
  pushd nspr &&
  make &&
  popd
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  pushd nspr &&
  make install &&
  popd &&
  echo "INSTALL COMPLETE"
}
