#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  install -v -m755 -d /usr/share/doc/gnupg-1.4.13 &&
  mv -v /usr/share/gnupg/FAQ /usr/share/doc/gnupg-1.4.13 &&
  install -v -m644 \
    doc/{highlights-1.4.txt,OpenPGP,samplekeys.asc,DETAILS,*.texi} \
    /usr/share/doc/gnupg-1.4.13 &&
  echo "INSTALL COMPLETE"
}
