#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make \
       docdir=/usr/share/doc/xfce4-power-manager-1.2.0 \
    imagesdir=/usr/share/doc/xfce4-power-manager-1.2.0/images \
    install &&
  echo "INSTALL COMPLETE"
}
