#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --with-all-insults \
    --enable-noargs-shell \
    --with-ignore-dot \
    --enable-shell-sets-home \
    --with-env-editor
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
