#!/bin/bash

function configure_commands()
{
   :
}

function make_commands()
{
  :
}

function test_commands()
{
  :
}

function install_commands()
{
  make prefix=/usr install &&
  echo "INSTALL COMPLETE"
}
