#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make -j1 -k check || echo "Darn $?"
}

function install_commands()
{
  make install &&
  install -v -m644 doc/Vorbis* /usr/share/doc/libvorbis-1.3.2 &&
  echo "INSTALL COMPLETE"
}
