#!/bin/bash

function configure_commands()
{
  sed -i -r 's:.*(#.*SUBPIXEL.*) .*:\1:' \
    include/freetype/config/ftoption.h &&
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
