#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  install -v -m755 -d /usr/share/doc/giflib-4.1.6/html &&
  install -v -m644 doc/*.{png,html} \
    /usr/share/doc/giflib-4.1.6/html &&
  install -v -m644 doc/*.txt \
    /usr/share/doc/giflib-4.1.6 &&
  echo "INSTALL COMPLETE"
}
