#!/bin/bash

function configure_commands()
{
  # --with-ca-certificates=/etc/ssl/ca-bundle.crt \
  ./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib/glib-networking \
    --disable-static \
    --without-ca-certificates
}

function make_commands()
{
  make
}

function test_commands()
{
  make -k check || echo "Darn $? ... oh well."
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
