#!/bin/bash

function configure_commands()
{
  sed -i 's:= @mkdir_p@:= /bin/mkdir -p:' po/Makefile.in.in &&
  ./configure --prefix=/usr &&
  sed -i 's@\(^#define DEFAULT_EDITOR_PROGRAM \).*@\1"vi"@' lib/config.h
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
