#!/bin/bash

# The method recommended by the Qt developers does not use the /usr directory prefix. It has the advantage of keeping all the package files consolidated in a dedicated directory hierarchy. By using this method, an update can be made without overwriting a previous installation and users can easily revert to a previous version by changing one symbolic link.

# The Qt developers use a default location of /usr/local/qt/, however the procedure below puts the files in /opt/qt-4.8.1/ and then creates a symbolic link to /opt/qt/.


function configure_commands()
{
  sed -i '/-Werror/d' src/3rdparty/webkit/Source/WebKit.pri &&
  ./configure \
            -prefix /opt/qt-4.8.1  \
            -release               \
            -nomake examples       \
            -nomake demos          \
            -system-sqlite         \
            -no-nis                \
            -opensource            \
            -confirm-license
}

function make_commands()
{
  make
}

function test_commands()
{
  make -k check || echo "DARN $? .... Oh, well."
}

function install_commands()
{
  make install &&
  ln -svfn qt-4.8.1 /opt/qt &&
  echo "INSTALL COMPLETE"
}
