#!/bin/bash

function configure_commands()
{
  false
}

function make_commands()
{
  : make
}

function test_commands()
{
  : make check
}

function install_commands()
{
  : make install-bootscripts &&
  : echo "INSTALL COMPLETE"
}
