#!/bin/bash

export FF_VERSION="28.0"

function configure_commands()
{
  cat > mozconfig << "EOF"
# If you have a multicore machine, firefox will now use all the cores by
# default. Exceptionally, you can reduce the number of cores, e.g. to 1,
# by uncommenting the next line and setting a valid number of CPU cores.
#mk_add_options MOZ_MAKE_FLAGS="-j1"

# If you have installed DBus-Glib comment out this line:
# ac_add_options --disable-dbus

# If you have installed wireless-tools comment out this line:
ac_add_options --disable-necko-wifi

# If you have installed libnotify comment out this line:
# ac_add_options --disable-libnotify

# GStreamer is necessary for H.264 video playback in HTML5 Video Player;
# to be enabled, also remember to set "media.gstreamer.enabled" to "true"
# in about:config. If you have installed GStreamer comment out this line:
# ac_add_options --disable-gstreamer

# Uncomment these lines if you have installed optional dependencies:
#ac_add_options --enable-system-hunspell
#ac_add_options --enable-startup-notification

# Comment out following option if you have PulseAudio installed
ac_add_options --disable-pulseaudio

# Uncomment this line if you compiled Cairo with --enable-tee switch and want
# to use it instead of the bundled one:
#ac_add_options --enable-system-cairo

# If you have not installed Yasm then uncomment this line:
# ac_add_options --disable-webm

# If you have installed xulrunner uncomment the next two ac_add_options lines
# and check that the sdk will be set by running pkg-config in a subshell
# and has not become hardcoded or empty when you created this file
#ac_add_options --with-system-libxul
#ac_add_options --with-libxul-sdk=$(pkg-config --variable=sdkdir libxul)

# Comment out following options if you have not installed
# recommended dependencies:
ac_add_options --enable-system-sqlite
ac_add_options --with-system-libevent
ac_add_options --with-system-libvpx
#ac_add_options --with-system-nspr
#ac_add_options --with-system-nss

# It is recommended not to touch anything below this line
ac_add_options --prefix=/usr
ac_add_options --enable-application=browser

ac_add_options --disable-crashreporter
ac_add_options --disable-installer
ac_add_options --disable-updater
ac_add_options --disable-debug
ac_add_options --disable-tests

ac_add_options --enable-optimize
ac_add_options --enable-strip
ac_add_options --enable-install-strip

ac_add_options --enable-gio
ac_add_options --enable-official-branding
ac_add_options --enable-safe-browsing
ac_add_options --enable-url-classifier

ac_add_options --enable-system-ffi
ac_add_options --enable-system-pixman

ac_add_options --with-pthreads

ac_add_options --with-system-bz2
ac_add_options --with-system-jpeg
ac_add_options --with-system-png
ac_add_options --with-system-zlib

mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/firefox-build-dir
EOF
}

function make_commands()
{
  # sed -i 's# ""##' browser/base/Makefile.in &&
  make -f client.mk &&
  make -C firefox-build-dir/browser/installer
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  rm -rf /usr/lib/firefox-${FF_VERSION} &&
  mkdir  /usr/lib/firefox-${FF_VERSION} &&
  tar -xvf firefox-build-dir/dist/firefox-${FF_VERSION}.en-US.linux-$(uname -m).tar.bz2 \
    -C /usr/lib/firefox-${FF_VERSION} --strip-components=1 &&
  # chown -R -v root:root /usr/lib/firefox-${FF_VERSION} &&
  # chmod -v 755 /usr/lib/firefox-${FF_VERSION}/libxpcom.so &&
  ln -sfv ../lib/firefox-${FF_VERSION}/firefox /usr/bin &&
  mkdir -pv /usr/lib/mozilla/plugins &&
  ln -sfv ../mozilla/plugins /usr/lib/firefox-${FF_VERSION} &&
  # echo "NPAPI Headers for gnash" &&
  # rm -rf /usr/include/npapi &&
  # mkdir -v /usr/include/npapi &&
  # cp -v dom/plugins/base/*.h /usr/include/npapi &&
  echo "INSTALL COMPLETE"
}
