#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --docdir=/usr/share/doc/dbus-python-1.0.0
}

function make_commands()
{
  make
}

function test_commands()
{
  make -k check || echo "Darn $? ... oh, well."
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
