#!/bin/bash

function configure_commands()
{
  echo "no configure"
}

function make_commands()
{
  ./bootstrap.sh --prefix=/usr
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  ./b2 install link=shared &&
  echo "INSTALL COMPLETE"
}
