#!/bin/bash

SOURCE_DIR_PREFIX=libxdmcp

function configure_commands()
{
  ./configure $XORG_CONFIG
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
