#!/bin/bash

function configure_commands()
{
  sed -i 's/#include <stdio.h>/&\n#include <string.h>/' \
    examples/cpp/encode/file/main.cpp &&
  ./configure \
    --prefix=/usr \
    --enable-sse \
    --disable-static \
    --disable-thorough-tests
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
