#!/bin/bash

function configure_commands()
{
  sed -i "s/pthread-stubs//" configure &&
  ./configure $XORG_CONFIG      \
     --enable-xinput \
     --without-doxygen \
     --docdir='${datadir}'/doc/libxcb-1.12
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
