#!/bin/bash
function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --bindir=/bin \
    --docdir=/usr/share/doc/sed-4.2.2
}

function make_commands()
{
  make &&
  make html
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  make -C doc install-html &&
  echo "INSTALL COMPLETE"
}
