#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --docdir=/usr/share/doc/terminal-0.4.8
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
