#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --program-prefix="eu-"
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
