#!/bin/bash
function configure_commands()
{
  FORCE_UNSAFE_CONFIGURE=1 \
  ./configure \
   --prefix=/usr \
    --enable-no-install-program=kill,uptime \
    --enable-install-program=hostname \
    --libexecdir=/usr/lib
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install || exit $?
  mv -v /usr/bin/{cat,chgrp,chmod,chown,cp,date} /bin
  mv -v /usr/bin/{dd,df,echo,false,hostname,ln,ls,mkdir,mknod} /bin
  mv -v /usr/bin/{pwd,rm,rmdir,stty,true,uname} /bin
  mv -v /usr/bin/chroot /usr/sbin
  echo "INSTALL COMPLETE"
}
