#!/bin/bash

function configure_commands()
{
  ABI=32 \
  CC="gcc -isystem /usr/include" \
  CXX="g++ -isystem /usr/include" \
  LDFLAGS="-Wl,-rpath-link,/usr/lib:/lib" \
  ./configure \
    --prefix=/usr \
    --enable-cxx \
    --docdir=/usr/share/doc/gmp-6.0.0
}

function make_commands()
{
  make &&
  make html
}

function test_commands()
{
  make -k check
}

function install_commands()
{
  make install &&
  make install-html &&
  echo "INSTALL COMPLETE"
}
