#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --with-zlib \
    --with-bzlib
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
