#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --docdir=/usr/share/doc/flex-2.5.39
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "The test suite will report 3 failures for tests that use bison,"
  echo " which is not installed yet."
  make -k check || echo "nevermind"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
