#!/bin/bash

function configure_commands()
{
  FORCE_UNSAFE_CONFIGURE=1 \
    ./configure \
      --prefix=/usr \
      --bindir=/bin \
      --libexecdir=/usr/sbin
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  perl tarman > /usr/share/man/man1/tar.1 &&
  make -C doc install-html docdir=/usr/share/doc/tar-1.26 &&
  echo "INSTALL COMPLETE"
}
