#!/bin/bash

function configure_commands()
{
  sed -i -e "s|BUILD_ZLIB\s*= True|BUILD_ZLIB = False|"           \
       -e "s|INCLUDE\s*= ./zlib-src|INCLUDE    = /usr/include|" \
       -e "s|LIB\s*= ./zlib-src|LIB        = /usr/lib|"         \
    cpan/Compress-Raw-Zlib/config.in &&
  sh Configure \
      -des \
      -Dprefix=/usr                 \
      -Dvendorprefix=/usr           \
      -Dman1dir=/usr/share/man/man1 \
      -Dman3dir=/usr/share/man/man3 \
      -Dpager="/usr/bin/less -isR"  \
      -Duseshrplib
}

function make_commands()
{
  make
}

function test_commands()
{
  make test
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
