#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --disable-static
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make docdir=/usr/share/doc/libdaemon-0.14 install &&
  echo "INSTALL COMPLETE"
}
