#!/bin/bash

export BUILD_DIR=build_graphite
export GRAPHITE2_SRC_DIR=$HOME/graphite2-1.3.8

function configure_commands()
{
  sed -i '/cmptest/d' $GRAPHITE2_SRC_DIR/tests/CMakeLists.txt &&
  cmake \
   -DCMAKE_INSTALL_PREFIX=/usr \
   -DCMAKE_VERBOSE_MAKEFILE=ON \
   $GRAPHITE2_SRC_DIR
}

function make_commands()
{
  make
}

function test_commands()
{
  make test
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
