#!/bin/bash

function configure_commands()
{
  echo "no configure"
}

function make_commands()
{
  ./help2man -N --include ./lsb_release.examples \
    --alt_version_key=program_version ./lsb_release > lsb_release.1
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  install -v -m 644 lsb_release.1 /usr/share/man/man1/lsb_release.1 &&
  install -v -m 755 lsb_release /usr/bin/lsb_release &&
  echo "INSTALL COMPLETE"
}
