#!/bin/bash

function configure_commands()
{
  echo "no configure"
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make \
    MAN_USER=sysklogd \
    MAN_GROUP=sysklogd \
    BINDIR=/sbin \
    install &&
  echo "INSTALL COMPLETE"
}
