#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
 echo "no make check"
}

function install_commands()
{
  make install &&
  install -v -m755 -d      /usr/share/doc/poppler-0.18.4 &&
  install -v -m644 README* /usr/share/doc/poppler-0.18.4 &&
  echo "INSTALL COMPLETE"
}
