#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --system-libs \
    --mandir=/share/man \
    --docdir=/share/doc/cmake-2.8.7
}

function make_commands()
{
  make
}

function test_commands()
{
  make -k test || echo "DARN $? ... oh, well."
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
