#!/bin/bash

function configure_commands()
{
  sed "s@AM_CONFIG_HEADER@AC_CONFIG_HEADERS@g" -i configure.ac &&
  autoreconf -fi &&
  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    CFLAGS="-fPIC"
}

function make_commands()
{
  make
}

function test_commands()
{
 :  make check
}

function install_commands()
{
  make install &&
  mv -v /usr/lib/libtirpc.so.* /lib &&
  ln -sfv ../../lib/libtirpc.so.1.0.10 /usr/lib/libtirpc.so &&
  echo "INSTALL COMPLETE"
}
