#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --bindir=/bin \
    --without-bash-malloc \
    --with-installed-readline \
    --docdir=/usr/share/doc/bash-4.3
}

function make_commands()
{
  make
}

function test_commands()
{
  : # make tests # this is broken: just dies
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
