#!/bin/bash

function configure_commands()
{
  sed -i -e 's/\ sulogin[^ ]*//' \
         -e 's/pidof\.8//' \
         -e '/ln .*pidof/d' \
         -e '/utmpdump/d' \
         -e '/mountpoint/d' \
         -e '/mesg/d' src/Makefile &&
  sed -i -e 's@! -p /dev/initctl@1 = 2@' src/Makefile
}

function make_commands()
{
  make -C src clobber
  make -C src
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make -C src install &&
  echo "INSTALL COMPLETE"
}
