#!/bin/bash

function configure_commands()
{
  sed -i 's@Sending processes@& configured via /etc/inittab@g' src/init.c &&
  sed -i -e 's/utmpdump wall/utmpdump/' \
         -e '/= mountpoint/d' \
         -e 's/mountpoint.1 wall.1//' src/Makefile &&
  make -C src clobber
}

function make_commands()
{
  make -C src
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make -C src install &&
  echo "INSTALL COMPLETE"
}
