#!/bin/bash

export BUILD_DIR=$HOME/build-libvpx

function configure_commands()
{
  sed -i 's/cp -p/cp/'  ../libvpx-*/build/make/Makefile &&
  chmod -v 644  ../libvpx-*/vpx/*.h &&
  ../libvpx-*/configure \
    --prefix=/usr \
    --enable-shared \
    --disable-static
}

function make_commands()
{
  make
}

function test_commands()
{
 :  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
