#!/bin/bash

function configure_commands()
{
  liblzma_CFLAGS="-I/usr/include" \
  liblzma_LIBS="-L/lib -llzma"    \
  zlib_CFLAGS="-I/usr/include"    \
  zlib_LIBS="-L/lib -lz"          \
  ./configure \
     --prefix=/usr       \
     --bindir=/bin       \
     --libdir=/lib       \
     --sysconfdir=/etc   \
     --with-xz           \
     --with-zlib
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make pkgconfigdir=/usr/lib/pkgconfig install
  for target in depmod insmod modinfo modprobe rmmod; do
    ln -sv ../bin/kmod /sbin/$target
  done
  ln -sv kmod /bin/lsmod
  echo "INSTALL COMPLETE"
}
