#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --bindir=/bin \
    --sysconfdir=/etc \
    --with-rootlibdir=/lib \
    --with-zlib \
    --with-xz
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  ln -sfv kmod /bin/lsmod &&
  for tool in depmod insmod modinfo modprobe rmmod; do
      ln -sfv ../bin/kmod /sbin/${tool}
  done &&
  echo "INSTALL COMPLETE"
}
