#!/bin/bash

function configure_commands()
{
  sed -i '/-fforce-mem/d' configure &&
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
