#!/bin/bash

function configure_commands()
{
  CC="gcc -isystem /usr/include" \
  CXX="g++ -isystem /usr/include" \
  LDFLAGS="-Wl,-rpath-link,/usr/lib:/lib" \
    ./configure \
      --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  mv -v /usr/lib/libz.so.* /lib &&
  ln -sfv ../../lib/$(readlink /usr/lib/libz.so) /usr/lib/libz.so &&
  mkdir -pv /usr/share/doc/zlib-1.2.8 &&
  cp -rv doc/* examples /usr/share/doc/zlib-1.2.8 &&
  echo "INSTALL COMPLETE"
}
