#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --disable-static
}

function make_commands()
{
  make
}

function test_commands()
{
  make -j1 -k check || echo "DARN $? .... Oh, well."
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
