#!/bin/bash

function configure_commands()
{
  echo "fix an issue with the russian man pages" &&
  sed -i 's/man_MANS = $(man_nopam) /man_MANS = /' man/ru/Makefile.in &&
  sed -i 's/groups$(EXEEXT) //' src/Makefile.in &&
  find man -name Makefile.in -exec sed -i 's/groups\.1 / /' {} \; &&
  sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
         -e 's@/var/spool/mail@/var/mail@' etc/login.defs &&
  ./configure \
    --sysconfdir=/etc \
    --with-group-name-max-length=64
}

function make_commands()
{
  make
}

function test_commands()
{
  echo 'no make check'
}

function install_commands()
{
  make install &&
  mv -v /usr/bin/passwd /bin &&
  echo "INSTALL COMPLETE"
}
