#!/bin/bash

function configure_commands()
{
  sed -i src/Makefile.in \
  -e 's/groups$(EXEEXT) //' -e 's/= nologin$(EXEEXT)/= /' &&
  find man -name Makefile.in -exec sed -i \
  -e 's/man1\/groups\.1 //' -e 's/man8\/nologin\.8 //' '{}' \; &&
  ./configure \
    --sysconfdir=/etc \
    --with-group-name-max-length=64
}

function make_commands()
{
  make
}

function test_commands()
{
  echo 'no make check'
}

function install_commands()
{
  make install &&
  sed -i /etc/login.defs \
    -e 's@#\(ENCRYPT_METHOD \).*@\1SHA512@' \
    -e 's@/var/spool/mail@/var/mail@' &&
  mv -v /usr/bin/passwd /bin &&
  echo "INSTALL COMPLETE"
}
