#!/bin/bash

function configure_commands()
{
  echo "no configure"
}

function make_commands()
{
  make USE_CAP=no \
    IPV4_TARGETS="tracepath ping clockdiff rdisc" \
    IPV6_TARGETS="tracepath6 traceroute6"
}

function test_commands()
{
  echo "no tests"
}

function install_commands()
{
  install -v -m755 ping /bin &&
  install -v -m755 clockdiff /usr/bin &&
  install -v -m755 rdisc /usr/bin &&
  install -v -m755 tracepath /usr/bin &&
  install -v -m755 trace{path,route}6 /usr/bin &&
  install -v -m644 doc/*.8 /usr/share/man/man8 &&
  echo "INSTALL COMPLETE"
}


# override CFLAGS, CXXFLAGS, or other environment variables here
# as needed.
#
# If the package needs to be built from a directory other than
# the source directory, set BUILD_DIR appropriately (for example:
# 'export BUILD_DIR=../build-binutils')
#
# You may copy a source tarball into a "src" subdirectory, and
# put patches into a "patches" subdirectory, in which case the
# build script will unpack and patch the source for you.
# Alternatively, you can prepare the source yourself (and cd into
# the source directory) before running build.
#
# If necessary, redefine the build functions:
#   configure_commands, make_commands, test_commands, install_commands
#
# If this package has external dependencies, such as requiring
# special users or groups to exist, verify that the dependencies
# are met in initial_checkup (echo problem notifications and exit
# if they are not).
#
# Look at ~/.bash_profile for syntax help.  Re-source the options
# file afterward!
#
# Run "declare -f" to find out the current function definitions.
#
# If you don't need to set anything in the options file, just
# delete it entirely!
