#!/bin/bash

function configure_commands()
{
  echo "no configure"
}

function make_commands()
{
  echo "no make"
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  install -v -d -m755 /usr/share/fonts/dejavu &&
  install -v -m644 ttf/*.ttf /usr/share/fonts/dejavu &&
  fc-cache -v /usr/share/fonts/dejavu &&
  echo "INSTALL COMPLETE"
}
