#!/bin/bash

BUILD_DIR=build

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --enable-shared \
    --disable-static \
    --enable-gpl \
    --enable-version3 \
    --enable-nonfree \
    --enable-runtime-cpudetect \
    --enable-openssl \
    --enable-libspeex \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libx264 \
    --enable-x11grab
}

function make_commands()
{
  make
  # && gcc ../tools/qt-faststart.c -o qt-faststart
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  # cp qt-faststart /usr/bin &&
  make install &&
#  mkdir /usr/share/doc/ffmpeg-0.10.3 &&
#  cp ../doc/*.txt /usr/share/doc/ffmpeg-0.10.3 &&
  echo "INSTALL COMPLETE"
}
