#!/bin/bash

function configure_commands()
{
  # i had to create  symlink to /usr/etc becuase of a bug which says
  # "/etc: no such file or directory
  # --sysconfdir=/etc
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
