#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr \
    --enable-shared \
    --disable-static \
    --with-ssl=openssl
}

function make_commands()
{
  make
}

function test_commands()
{
  make -j1 -k check || echo "DARN $?"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
